FROM ruby:3.2

RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs

WORKDIR /app

COPY Gemfile Gemfile.lock ./

RUN gem install bundler && bundle install || true

COPY . .

CMD ["rails", "server", "-b", "0.0.0.0"]
